### ISSUE TITLE
Check flag

### ISSUE THREAD

**Issue by williamjamir** [nedbat/cog#14]
Is it possible to run cog to check if a file will be changed?
If not, would it be possible to add a `--check` flag that returns a non-zero status code for CI and pre-commit purposes?

**Comment by hynek** [comment]
I would be interested in this too. That said, pre-commit also fails whenever a hook changes a file so it might be possible to achieve with an appropriate `.pre-commit-hooks.yaml` and no code changes.

**Comment by simonw** [comment]
I'd love this too - I came up with a workaround but it would be great if this was an available feature: https://til.simonwillison.net/python/cog-to-update-help-in-readme
