### ISSUE TITLE
Debian package: which release should be packaged?

### ISSUE THREAD

**Issue by dkogan** [nedbat/cog#25]
Hi. I was going to package the latest tag: v3.3.0. But doing that produces two different executables in `/usr/bin`. It looks like you already fixed that here: https://github.com/nedbat/cog/commit/29a5e049653947de339061ebd536837e7183045e

Should I wait for a new release of cog, or should I apply that change to v3.3.0? Debian is in a freeze right now (we're preparing our next release), so this won't make it into Debian for a few months anyway. So there's no rush on this at all.

Thanks!

**Comment by dkogan** [comment]
I packaged 3.3.0 , and pushed it into Debian.

**Comment by moriarty** [comment]
Just leaving some links here for anyone else who's looking for a debian of this. I was searching for this package it's called `python3-cogapp` in debian sid

https://tracker.debian.org/news/1458351/accepted-python-cogapp-330-2-source-all-into-unstable/

https://packages.debian.org/sid/python3-cogapp
