### ISSUE TITLE
Hosted module docs are blank

### ISSUE THREAD

**Issue by sco1** [nedbat/cog#28]
It appears that the module documentation is rendering as blank on RTD:

<img width="981" alt="image" src="https://github.com/nedbat/cog/assets/5323929/397416cd-f0b9-4946-914a-90f78315cceb">

(Firefox, similar in Safari)

If you click to [view the source](https://cog.readthedocs.io/en/latest/_sources/module.rst.txt) the content appears to be there, and it also looks fine [here on GitHub](https://github.com/nedbat/cog/blob/2f82c2703353321290a2b6e2e3f99f6b92908294/docs/module.rst). All of the package's other pages seem fine. Unfortunately I'm not familiar with deploying to RTD so I'm not sure how to help diagnose further at the moment.

**Comment by nedbat** [comment]
Thanks, i was in the middle of updating cog back in January, and forgot about it.  Now the page is correct.
