### ISSUE TITLE
Using cog with a markdown file and fenced code blocks

### ISSUE THREAD

**Issue by fmaida** [nedbat/cog#6]
Hello, I'm sorry to bother you but would it be possible to use cog with python snippets put between fenced code, inside a markdown file ?

For example can this markdown file:

    This is my source code

    ```python
    def sum_numbers(a, b):
        return a + b
    
    sum_numbers(3, 4)    
    ```

    and this is the result:

    ```cog
    ```

Be translated into this:
 
    This is my source code

    ```python
    def sum_numbers(a, b):
        return a + b
    
    sum_numbers(3, 4)    
    ```

    and this is the result:

    ```cog
    7
    ```

----
And then, getting this final output from a markdown parser:
----
 
This is my source code

```python
def sum_numbers(a, b):
    return a + b

sum_numbers(3, 4)    
```

and this is the result:

```cog
7
```

**Comment by nedbat** [comment]
You could use cog in a markdown file (HTML comments will be useful).  But I'm not sure there's a way to combine the HTML comments, Python comments, and Markdown triple-backticks in a way that will keep all of the software happy and produce the right result.

**Comment by fmaida** [comment]
Thank you.

**Comment by janto** [comment]
I was playing around and made the following that seems to work :)
https://gist.github.com/janto/2f779791b95e46c4abe7c9211af7a19b

(unable to paste the code here since the markdown gets interpreted)

which will give:

**Comment by janto** [comment]
This is a markdown file with some cog wrapped Python code...



which results in output like this



Markdown ends :)

**Comment by janto** [comment]
My version 2 that is shorter and gives color highlighting of python code in my editor:
https://gist.github.com/janto/c5176c5dc3968bdca146e59245ed4788
